### PR TITLE
Update Dockerfile to use Intel public ipex container

### PR DESCRIPTION
**Pull request by mattcurf**
Based on suggestion from https://github.com/mattcurf/ollama-intel-gpu/issues/10
Needs to be tested on Windows WSL

### CODE REVIEW

**Comment by pepijndevos** [comment]
Fyi I also removed the Unix socket and exposed the Ollama port but that's just personal needs and preferences

**Comment by embain14** [comment]
> Fyi I also removed the Unix socket and exposed the Ollama port but that's just personal needs and preferences

How would I go about doing this, I keep getting the following error and I think this may resolve my issue.
Ollama Error

**Comment by pepijndevos** [comment]
No I don't think either of those settings will solve your issue. 500 means the server crashed. But the docker compose logs should tell you what the actual error was.

**Comment by embain14** [comment]
#12 shows the full logs, I apologize if this is not the appropriate place to ask these types of questions. I'm very new to git and docker, learning more every day.

**Pull request merged**
